### ISSUE TITLE
Review Snaps documentation vs. actual features

### ISSUE THREAD

**Issue by ziad-saab** [MetaMask/snaps-monorepo#1002]
AC:
- [ ] Report on differences between docs and current Snaps features in Flask release

**Comment by ziad-saab** [comment]
https://docs.google.com/document/d/1MsYnHGWtsMdibkrLa7HEKJIEeHlwAou8mTf_uPd1dTE/edit?usp=sharing

This Google Doc contains my observations from going through the Snaps Documentation. It's still WIP

**Comment by kenhkan** [comment]
Christian will go through the list and create new tickets to address the inaccuracies. Closing this ticket.
