### ISSUE TITLE
Harden custom and common endowments and add tests

### ISSUE THREAD

**Issue by david0xd** [MetaMask/snaps-monorepo#1015]
This ticket is part of an epic: https://github.com/MetaMask/snaps-monorepo/issues/585

The purpose of this task is to introduce and test SES security functionalities in order to secure a custom and common endowments that are part of the `snaps-execution-environments` package.

Acceptance criteria:
Harden all custom endowments in the endowments folder and add tests.
Test common endowments security.

Notes:
This task will continue more organized and reasonable work after the spike research: https://github.com/MetaMask/snaps-monorepo/issues/1003

**Comment by kenhkan** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Snaps-615b3a7c08d2b20015eb6c4e/issues/MetaMask/snaps-monorepo/1015?planning-poker) with Zenhub @david0xd @FrederikBolding @GuillaumeRx @hmalik88 @Mrtenz @ritave

**Comment by david0xd** [comment]
Since this ticket was the research around the endowment security and some experimental development. I will close this ticket, and consider it done.

The work after the research is split, and followed in this ticket at first: https://github.com/MetaMask/snaps-monorepo/issues/1018
The PR with code changes is related to the ticket mentioned above and is here: https://github.com/MetaMask/snaps-monorepo/pull/1058

Results of the research done within this ticket:
- Established and implemented way of testing and [hardening common](https://github.com/MetaMask/snaps-monorepo/pull/1058) JavaScript (default) endowments.
- Established the security related work process and organization between the Snaps and Security team.
- Identified potential security threats with some of the endowments which are tracked in a separate tickets (#1150 #1132).
- Identified a specific need for hardening and paying more attention to the process for `snap` and `ethereum` endowment (#1017).
