### ISSUE TITLE
Additionally harden custom endowments

### ISSUE THREAD

**Issue by david0xd** [MetaMask/snaps-monorepo#1017]
The definition of this ticket should be based on a research done for hardening custom endowments: https://github.com/MetaMask/snaps-monorepo/issues/1152

Based on the research it is determined that `ethereum` and `snap` endowments should follow the hardening process of the previous hardening work for common (JavaScript) endowments.

It is required for the proxy to be modified in order to prevent `harden` function reaching and freezing the parts of the StreamProvider. Solution for that is found and experimented in the PR: https://github.com/MetaMask/snaps-monorepo/pull/1172

**Comment by Montoya** [comment]
Would consider this to be done when a snap cannot modify the endowments or use them to escape its sandbox.
