### ISSUE TITLE
Additionally harden common endowments

### ISSUE THREAD

**Issue by david0xd** [MetaMask/snaps-monorepo#1018]
Previously common (now custom) endowments should be hardened in a more proper way after the first iteration that is followed in this ticket: https://github.com/MetaMask/snaps-monorepo/issues/1015 (PR: https://github.com/MetaMask/snaps-monorepo/pull/1058)

This ticket is part of an epic: https://github.com/MetaMask/snaps-monorepo/issues/585

Constructor functions are target for the hardening in this ticket and are presented in the table below:
| Endowment        | Type             |
| ---------------- | ---------------- |
| BigInt | constructor |
| Date | constructor |
| SubtleCrypto | constructor |
| TextDecoder | constructor |
| TextEncoder | constructor |
| URL | constructor |
| Int8Array | constructor |
| Uint8Array | constructor |
| Uint8ClampedArray | constructor |
| Int16Array | constructor |
| Uint16Array | constructor |
| Int32Array | constructor |
| Uint32Array | constructor |
| Float32Array | constructor |
| Float64Array | constructor |
| BigInt64Array | constructor |
| BigUint64Array | constructor |
| DataView | constructor |
| ArrayBuffer | constructor |
| AbortController | constructor |
| AbortSignal | constructor |

Additional hardening methods that should be considered in this work are a proxy or a specific wrapper that will be the outer shell of an instance of a specific class.

**Comment by anarasam** [comment]
добрый день Виталик!  я участвовала  в дефай  проект мелон  я открыла там  фонд  и положила 1weth   в мета маск он показывает  у меня есть одна монетка 1MLNF  Ккак мне  обратно  вернуть  эфирки  мне нужно оплатить за обучение  ребенка . Пожалуйста помогитеhttps://etherscan.io/token/0x7b47ddd49cd595ae0b074f2b8e82c7848e4e20f5?a=0x0c4ca96d4e63af64fb7896ab41e0aa871a59fabb  в кошелке мета маск есть 1weth как вернуть деньги

**Comment by anarasam** [comment]
good afternoon Vitalik! I participated in the defi melon project I opened a fund there and lost 1weth in the meta disguise it shows I have one 1MLNF coin How do I get back the ethers I need to pay for the child's education. Please help https://etherscan.io/token/0x7b47ddd49cd595ae0b074f2b8e82c7848e4e20f5?a=0x0c4ca96d4e63af64fb7896ab41e0aa871a59fabb in wallet meta money mask 1weth how to get money back

**Comment by Montoya** [comment]
Consider using proxies instead of hardening each individual endowment with custom wrappers, and only harden the return if it returns something other than itself.
