### ISSUE TITLE
Buffer endowment 

### ISSUE THREAD

**Issue by paulfears** [MetaMask/snaps-monorepo#1021]
Hello, is there a way to request the buffer endowment like the network-request endowment? some of the dependencies I use rely on a global Buffer.

**Comment by ritave** [comment]
There's not `Buffer` on the web. You can use the [Buffer polyfill from npm](https://www.npmjs.com/package/buffer) instead.

**Comment by paulfears** [comment]
Won't a polyfill not have global access in the snap. it used to be there in an old version of the compiler

**Comment by Montoya** [comment]
I am not sure about that but you can modify the browserify bundler to add any polyfill: https://github.com/MetaMask/snaps-monorepo/tree/main/packages/snaps-cli#configuration-file

**Comment by paulfears** [comment]
I still can't globally insert Buffer even when using a Transform




Is there a way I can modify the compiler to re-add buffer as a global like the old version of the compiler
Code compiles fine in version 20.0.0 but one of the packages I am using has more than 2000 instances of Buffer.from, and its not feasible to patch every one.

maybe I'm doing something wrong
This is the snaps config file, but I still get an SES error about Buffer.from not being defined

var insert = require('insert-module-globals');


function inserter (file) {

  const inserterThing = insert(file);
  return inserterThing;
}

module.exports = {
  cliOptions: {
    src: './src/index.ts',
    port: 8080,
  },
  bundlerCustomizer: (bundler) => {
    return bundler.transform(inserter, {global:true})
  },
};

**Comment by FrederikBolding** [comment]
@paulfears Couldn't you polyfill the global `Buffer` like this in your snap entrypoint?

```
globalThis.Buffer = require('buffer/').Buffer;
// Other imports

export const onRpcRequest = (...) => { ... }
```

**Comment by FrederikBolding** [comment]
@paulfears Couldn't you polyfill the global `Buffer` like this in your snap entrypoint?

```
globalThis.Buffer = require('buffer/').Buffer;
// Other imports

export const onRpcRequest = (...) => { ... }
```

**Comment by paulfears** [comment]
Awesome, this worked for me, but I had to combine it with patch-patch package, and it to the specific entry point of the node_modules that required it, I guess its a small price to pay for everything working. Very thankful for the help -cheers

**Comment by taijusanagi** [comment]
Hi, I encounter the same issue and tried putting polyfill in the Metamask snap entry point, but it did not work for me.

I checked the bundle.js generated by mm-snap, and the Buffer polyfill line is placed below this library initialization, even though I put it in the entry point - before all import library codes.

Instead, I put the polyfill in the dependency library's endpoint, and it fixed the issue.
