### ISSUE TITLE
Document network access as a feature

### ISSUE THREAD

**Issue by Montoya** [MetaMask/snaps-monorepo#1028]
In the list of features in the first section of the snaps documentation, we should include a feature like "Access the Internet" and link to the network-access reference documentation. 

https://docs.metamask.io/snaps/reference/permissions#endowmentnetwork-access

Also, the network access reference documentation mentions `WebSocket` as a feature but we should remove that mention for now since WebSocket is not very useful yet.

**Comment by ziad-saab** [comment]
Fixed by https://github.com/MetaMask/metamask-docs/pull/766
