### ISSUE TITLE
`eth_accounts` and `eth_requestAccounts` always return the same address

### ISSUE THREAD

**Issue by andyv09** [MetaMask/snaps-monorepo#1063]
As mentioned in the title, the mentioned functions always return the same first address even after switching accounts in MetaMask and connecting with another account. I can switch to Account 2 and connect with it to a dApp, but will still get Account 1s address when calling the mentioned RPC methods.

Im using snaps 0.26.0 and build from MetaMask extension develop branch.

**Comment by FrederikBolding** [comment]
I believe this is a symptom of https://github.com/MetaMask/snaps-monorepo/pull/1064

**Comment by FrederikBolding** [comment]
@andyv09 Can you check the latest `develop` branch to see if you still are having this issue? I believe this should be fixed.

**Comment by andyv09** [comment]
This issue is fixed in the new `develop` branch.
