### ISSUE TITLE
Ensure `endowment:network-access` is platform-agnostic.

### ISSUE THREAD

**Issue by ritave** [MetaMask/snaps-monorepo#1068]
All the APIs we expose concerning the network access should be platform agnostic.

The platforms include
* Chrome
* Brave
* Firefox
* NodeJS.

The exposed APIs, at the moment, include:
* `fetch`
* `WebSockets` (no longer relevant as we are not exposing this now)

The ticket can be considered done when we have unit tests for all the platforms/APIs.

**Comment by kenhkan** [comment]
We need to spend some time to see if this is still relevant.

**Comment by hmalik88** [comment]
The `fetch` API is available across Firefox, Chrome and Brave. In NodeJS, it was available from v18 onwards. Will our execution environment ever be in < Node v18 environment? If not, we can write tests to test the `fetch` API across the different platforms. Not sure if this is really necessary though?

**Comment by kenhkan** [comment]
Closing this ticket as this is irrelevant now. We will look into how to handle endowments that don't work in a separate initiative.
