### ISSUE TITLE
Research how to harden common endowments

### ISSUE THREAD

**Issue by Montoya** [MetaMask/snaps-monorepo#1093]
This ticket should focus on finding a way how to harden specific endowments such as endowments that are constructor functions.

One of the suggestion was using Proxies, so that should be one of the starting points for this research.

This ticket will unblock and refine the following tickets:
https://github.com/MetaMask/snaps-monorepo/issues/1018
https://github.com/MetaMask/snaps-monorepo/issues/1017

In general, constructor functions are target for the hardening and are presented in the table below:
| Endowment        | Type             |
| ---------------- | ---------------- |
| BigInt | constructor |
| SubtleCrypto | constructor |
| TextDecoder | constructor |
| TextEncoder | constructor |
| URL | constructor |
| Int8Array | constructor |
| Uint8Array | constructor |
| Uint8ClampedArray | constructor |
| Int16Array | constructor |
| Uint16Array | constructor |
| Int32Array | constructor |
| Uint32Array | constructor |
| Float32Array | constructor |
| Float64Array | constructor |
| BigInt64Array | constructor |
| BigUint64Array | constructor |
| DataView | constructor |
| ArrayBuffer | constructor |
| AbortController | constructor |
| AbortSignal | constructor |

**Comment by david0xd** [comment]
After consulting with a Security Team, we identified some approaches how this should be done.
There are two phases of testing identified:
1. Trying to make changes to the endowments which should not be possible at all (_hardening with harden() SES function_).
2. Searching all objects for `globalThis` references which exposure to the snap should be prevented.

Several testing approaches are implemented to ensure the security.
Further manual in-detail security audit of the JavaScript intrinsic objects might be required to fully confirm security of it which possibly can be addressed in the two remaining tickets in this epic.
