### ISSUE TITLE
Disable `endowment:long-running` in stable

### ISSUE THREAD

**Issue by ritave** [MetaMask/snaps-monorepo#1103]
#945 requires rethinking a new API to allow useful Snap use-cases that used this behaviour before.

It's important to support those case, but we also want to avoid scope creep for v1.0.0 release of Snaps.

### Outcome
* Disable `endowment:long-running` in stable altogether and post a deprecation warning in Flask
* Add a console warning when using that permission in Flask explaning the deprecation and pointing to a github issue / discussion.

**Comment by FrederikBolding** [comment]
Do we just want to remove it in its entirety until we come up with a new solution? Otherwise, we will have to maintain it even though it isn't in use.

**Comment by FrederikBolding** [comment]
We agreed in a prioritization call to disable for now in stable and remove all together once we have a replacement API.

**Comment by GuillaumeRx** [comment]
Use the new `SnapController` arg `excludedPermissions` introduced in #1125 to retrict it on the extension side.

**Comment by FrederikBolding** [comment]
This has not been completed yet...

**Comment by FrederikBolding** [comment]
Closing for now since it is technically fenced correctly, but we should remember to keep the fencing as-is when we remove the Flask fencing.
