### ISSUE TITLE
Update `SnapController` & `MultiChainController` to use caveats  

### ISSUE THREAD

**Issue by hmalik88** [MetaMask/snaps-monorepo#1105]
Please refer to parent issue [#297](https://github.com/MetaMask/MetaMask-planning/issues/297)

The `SnapController` and `MultiChainController` needs to be updated to now use caveats to check for dapp <-> snap permissions and similarly to revoke snap permissions.

**Comment by FrederikBolding** [comment]
Closed as part of https://github.com/MetaMask/snaps-monorepo/pull/1180
