### ISSUE TITLE
State transition error during upgrade

### ISSUE THREAD

**Issue by ritave** [MetaMask/snaps-monorepo#1110]
When Keystone's BTC snap is upgraded from 1.1.0 to 1.2.0, an error occurs in Flask.

```json
{
    "npm:btcsnap": {
        "error": {
            "code": -32603,
            "message": "Invalid state transition",
            "data": {
                "originalError": {
                    "code": "ERR_ASSERTION"
                }
            }
        }
    }
}
```

The error is related to xstate state transition in SnapController in some way.

**Comment by FrederikBolding** [comment]
I was unable to reproduce this as-is, but I realized at least one way this error could be triggered is if the existing snap is in a crashed state, you cannot update it. A proposed fix is available for that here: https://github.com/MetaMask/snaps-monorepo/pull/1113
