### ISSUE TITLE
using Emscripten inside a snap

### ISSUE THREAD

**Issue by firnprotocol** [MetaMask/snaps-monorepo#1131]
hi all, i am encountering issues running Emscripten-generated JavaScript inside of a snap. here's the setup: after compiling a minimal C++ file using Emscripten (see MWE [here](https://github.com/herumi/misc/tree/main/wasm/sample)), an [auto-generated JavaScript file](https://github.com/herumi/misc/blob/main/wasm/sample/src/sample_c.js) results. upon importing this file within a snap, errors result. a detailed description of the errors is given in [this comment](https://github.com/herumi/mcl-wasm/issues/28#issuecomment-1378173673).

these errors are _prior_ to the invocation of WebAssembly, and take place during the Emscripten preparation code. they have to do with the fact that `document === undefined` in the SES environment within a Snap, and also from the fact that the semantics of `fetch()` appear different (the returned result has no `.then()` member).

an end-to-end MWE using snaps is given in [this repo](https://github.com/firnprotocol/snap-mcl-wasm-mwe/tree/cdbaba5dd06e2136ceedff2515580a5da09e84a4/packages/snap).

reproducing a minimal SES-only example (without Snaps) is very hard, since there is a lot of Snap-specific setup code. i am working on this.

any advice would be greatly appreciated! thanks in advance. cc. @herumi.

**Comment by FrederikBolding** [comment]
`fetch` should not be different in the snaps execution environment. I tested locally just now and was able to use `.then()` chaining on the `fetch` promise. Could you elaborate on how that isn't working for you?

Also, it looks like this issue was solved at the dependency level already? Let me know if that isn't the case. Regardless my advice would be the same, you would need to patch the dependency to remove the logic that is unsupported in SES. We have an article on this here: https://docs.metamask.io/guide/snaps-patching-dependencies.html#patching-dependencies

**Comment by firnprotocol** [comment]
> fetch should not be different in the snaps execution environment. I tested locally just now and was able to use .then() chaining on the fetch promise. Could you elaborate on how that isn't working for you?

my issue was something like `.then is not a function`, even though [this line](https://github.com/firnprotocol/snap-mcl-wasm-mwe/blob/9c8458238381339ed877a629c46020f6f2c25e5a/packages/snap/sample/src/sample_c.js#L1617) went through, meaning `fetch` _is_ a function. no idea why; i didn't get a chance to investigate it further. in any case, this issue alone won't be enough regardless, since we still have the `scriptDirectory.indexOf` issue.

> Also, it looks like the originally reported issue was solved at the dependency level already?

it was, but the solution is not so ideal, since it (conceivably) could have unintended effects on other users.

> Regardless my advice would be the same, you would need to patch the dependency to remove the logic that is unsupported in SES.

i prefer this solution to what we've already done. unfortunately, `patch-package` gives me completely inscrutable errors:
```javascript
snap % yarn patch-package mcl-wasm
patch-package 6.5.1
• Creating temporary folder
• Installing mcl-wasm@1.0.3 with yarn

{
  status: 1,
  signal: null,
  output: [
    null,
    <Buffer 1b 5b 33 31 6d 1b 5b 31 6d 55 6e 6b 6e 6f 77 6e 20 53 79 6e 74 61 78 20 45 72 72 6f 72 1b 5b 32 32 6d 1b 5b 33 39 6d 3a 20 55 6e 73 75 70 70 6f 72 74 ... 142 more bytes>,
    <Buffer >
  ],
  pid: 41354,
  stdout: <Buffer 1b 5b 33 31 6d 1b 5b 31 6d 55 6e 6b 6e 6f 77 6e 20 53 79 6e 74 61 78 20 45 72 72 6f 72 1b 5b 32 32 6d 1b 5b 33 39 6d 3a 20 55 6e 73 75 70 70 6f 72 74 ... 142 more bytes>,
  stderr: <Buffer >,
  error: null
}

/Users/____________/snap/node_modules/patch-package/dist/makePatch.js:218
        throw e;
```
do these ring any bells? thanks.

**Comment by firnprotocol** [comment]
update: i was able to solve the issue with `patch-packages` (modulo a bit of tweaking to get the patch generated in the first place).

thank you!
