### ISSUE TITLE
Threat Modeling - wallet_getSnaps - Information Disclosure

### ISSUE THREAD

**Issue by bentobox19** [MetaMask/snaps-monorepo#1143]
Confirming that in order for the RPC method `wallet_getSnaps` to work, a dApp needs to be **connected** to the extension.

If this is true we can discard the following threat:

**Information Disclosure**: An attacker can build a malicious dApp, phishing users into accessing its website, collecting information about their installed snaps.

**Comment by FrederikBolding** [comment]
`wallet_getSnaps` only returns snaps that the requesting DApp has permission to talk to. Meaning a dapp has to be "connected" to a snap for it to show up in the result of `wallet_getSnaps`.

For reference: https://github.com/MetaMask/snaps-monorepo/blob/main/packages/snaps-controllers/src/snaps/SnapController.ts#L1489

**Comment by kenhkan** [comment]
@bentobox19 Olaf, David, and I are going through security tickets. Frederik has invalidated the case. Please close the ticket or raise additional question that you may have.
