### ISSUE TITLE
Threat Modeling - wallet_invokeSnaps - Repudiation

### ISSUE THREAD

**Issue by bentobox19** [MetaMask/snaps-monorepo#1144]
Confirming that snaps RPC methods don't log parameters.

If this statement is true, we should consider within the threat model that an attacker can repudiate that a kill chain leveraged the method `wallet_invokeSnaps`.

Proposed control: Log parameters `method` and `params.snapId`.

**Comment by FrederikBolding** [comment]
All RPC requests are logged to the MetaMask state logs that can be exported by users and passed on to support. `wallet_invokeSnap` is currently logged as
```
      {
        "id": 4078008060,
        "method": "wallet_invokeSnap",
        "methodType": "internal",
        "origin": "http://localhost:8000",
        "requestTime": 1674130770966,
        "responseTime": 1674130831045,
        "success": false
      },
```
