### ISSUE TITLE
Threat Modeling - wallet_requestSnaps - Repudiation

### ISSUE THREAD

**Issue by bentobox19** [MetaMask/snaps-monorepo#1146]
Can an attacker leveraging the method `wallet_requestSnaps` to install a malicious snap be detected?

Proposed Control: Log the Snap ID to be installed.

**Comment by FrederikBolding** [comment]
All RPC requests are logged to the MetaMask state logs that can be exported by users and passed on to support. `wallet_requestSnaps` is currently logged as
```
      {
        "id": 2927843613,
        "method": "wallet_requestSnaps",
        "methodType": "internal",
        "origin": "http://localhost:8080",
        "requestTime": 1673976464991,
        "responseTime": 1673976469357,
        "success": true
      },
```
