### ISSUE TITLE
Threat Modeling - wallet_requestSnaps - Denial of Service

### ISSUE THREAD

**Issue by bentobox19** [MetaMask/snaps-monorepo#1147]
Please confirm the existence of size limits for:

* fetching
* extracting

The proposed threat regarding _Denial of Service_ being:

> An attacker can abuse the size limit of either fetching or extracting to provoke a failure on availability.

**Comment by FrederikBolding** [comment]
Tarball extraction has a size limit of 250 MB: https://github.com/MetaMask/snaps-monorepo/blob/main/packages/snaps-controllers/src/snaps/location/npm.ts#L296-L297

I'm opening a PR here to establish a tarball size limit for the fetched tarball as well: https://github.com/MetaMask/snaps-monorepo/pull/1169
