### ISSUE TITLE
Threat Modeling - wallet_requestSnaps - Denial of Service

### ISSUE THREAD

**Issue by bentobox19** [MetaMask/snaps-monorepo#1148]
Confirm that the installing of snaps is always controlled by the UI, as will that the installing process are always queue in a synchronous manner.

**Comment by FrederikBolding** [comment]
One permission request of each type is allowed per origin currently and enforced by the `ApprovalController`. Anything outside of those limits will be automatically rejected: https://github.com/MetaMask/core/blob/8872c9b5c636c5e258198547181e35c59d0bc2b7/packages/approval-controller/src/ApprovalController.ts#L490-L494

We should make sure this is still the case after we finish #1119 and https://github.com/MetaMask/MetaMask-planning/issues/297
