### ISSUE TITLE
Threat Modeling - snap_dialog - Spoofing

### ISSUE THREAD

**Issue by bentobox19** [MetaMask/snaps-monorepo#1158]
Reviewing the Threat Model for `snap_dialog` we found that:

> An attacker can craft a dialog from Snap B to look like coming from Snap A.

Opening this issue to discuss eventual controls to this threat.

**Comment by FrederikBolding** [comment]
I'm not sure I understand this entirely. How is the spoofing possible? We are showing the name of the snap etc in the UI to help distinguish.
