### ISSUE TITLE
Threat Modeling - snap_dialog - Repudiation

### ISSUE THREAD

**Issue by bentobox19** [MetaMask/snaps-monorepo#1159]
The RPC method `snap_dialog` can be leveraged for phishing.

Proposed Control: Improve logging of the RPC method.

**Comment by FrederikBolding** [comment]
All RPC requests are logged to the MetaMask state logs that can be exported by users and passed on to support. `wallet_requestSnaps` is currently logged as
```
      {
        "id": 1359768542,
        "method": "snap_dialog",
        "methodType": "restricted",
        "origin": "local:http://localhost:8010",
        "requestTime": 1673976480086,
        "responseTime": 1673976483826,
        "success": true
      },
```
