### ISSUE TITLE
Issues with WASM of >4Kb

### ISSUE THREAD

**Issue by immortal-tofu** [MetaMask/snaps-monorepo#1160]
Hello!
I'm developing a snap that needs to load a 1Mb wasm. If you need to load a wasm >4kb, you can't use `WebAssembly.instantiate`, you need to use `WebAssembly.instantiateStreaming` as follow: `WebAssembly.instantiateStreaming(fetch('mymodule.wasm'))`.

**Issue 1**
You can't bundle a snap with a `.wasm` file, so if you need to use `WebAssembly.instantiateStreaming`, you'd need to fetch the wasm from an external website. This is not something you want to do.
It would be great to allow user to add a wasm in the bundle (declared in manifest maybe) and have the possibility to load it. It would be also great to have the possibility to load it without the "internet connection" permission (since you'd load it locally)

**Issue 2**
Since loading a wasm from an external website is not something I want to do, I encapsulated everything as base64 in the js file. Even with this solution, it's not trivial to use. `WebAssembly.instantiateStreaming` expect a native `Response` object. In SES, you don't have access to this native object... except if you have the "internet connection" permission 😃  You don't use fetch, but still, you need to ask this permission.

**Issue 3**
If you're using `wasm-pack`, it will use `self.self` to give `window` object to the wasm. In the declared global by Metamask, `global.self` is not defined. I would be useful to automatically declare variables such as `global.self = global` or `global.window = global` to avoid issue with some libraries.

**Issue 4**
It was impossible to make things work with mm-snap and I needed to use webpack to wire everything.

**State of the art to load a wasm >4Kb**

Here an example on how to load wasm file in snap (generated with wasm-pack):

```
import init from 'module-using-wasm-pack-export';
import wasm from 'module-using-wasm-pack-export/tfhe_bg.wasm';
import { base64ToArrayBuffer } from './utils';

export const loadWasm = async () => {
  // wasm is the base64 generated on compile by webpack
  const bytes = base64ToArrayBuffer(wasm.split(',')[1]);

  // IMPORTANT trick to allow wbindgen to find window -.-
  self.self = self;

  // generate a Response object with wasm in it
  const response = new Response(bytes, {
    headers: new Headers({
      'Content-Type': 'application/wasm',
    }),
  });

  // Use init function provided by wasm-pack, which basically do an WebAssembly.instantiateStreaming with correct imports generated by wbindgen
  return init(Promise.resolve(response));
};
```

**Comment by Niraj-Kamdar** [comment]
Hey, @immortal-tofu I am also working with the Wasm in Metamask snap and having an issue related to buffer since they stopped polyfilling it. I noticed you had issue with mm-snap and used webpack to manually create bundle.js 

Can you share with me a snippet of code and webpack config that you used to fix issue 4?

I am also curious to know why we can't instantiate a Wasm module with more than 1MB size?

**Comment by immortal-tofu** [comment]
> Hey, @immortal-tofu I am also working with the Wasm in Metamask snap and having an issue related to buffer since they stopped polyfilling it. I noticed you had issue with mm-snap and used webpack to manually create bundle.js
> 
> Can you share with me a snippet of code and webpack config that you used to fix issue 4?
> 
> I am also curious to know why we can't instantiate a Wasm module with more than 1MB size?
You need to add these fallbacks to make it work in `webpack.config.js`
```
  resolve: {
    fallback: {
      buffer: require.resolve('buffer/'),
      crypto: require.resolve('crypto-browserify'),
      stream: require.resolve('stream-browserify'),
      path: require.resolve('path-browserify'),
    },
  },
```

I don't think there is a limit of 1Mb technically. There is limit of 4Kb, because beyond 4Kb you can't load it with `WebAssembly.instantiate`.

**Comment by Niraj-Kamdar** [comment]
Oh 4Kb, that shouldn't be the case. We have been executing Wasm modules with way more sizes than that. Although we are fetching the Wasm module at runtime from the IPFS. You can checkout Polysnap: https://devfolio.co/projects/polysnap-8c87

We have executed this module: https://wrappers.io/v/ipfs/QmXDrNvjpGeQ84hNELv4smTjQQB3BYYB2ahAT9DdvZ6Fsc successfully which was 90KB in size and we are using WebAssembly.instantiate for this.

**Comment by immortal-tofu** [comment]
> Oh 4Kb, that shouldn't be the case. We have been executing Wasm modules with way more sizes than that. Although we are fetching the Wasm module at runtime from the IPFS. You can checkout Polysnap: https://devfolio.co/projects/polysnap-8c87
> 
> We have executed this module: https://wrappers.io/v/ipfs/QmXDrNvjpGeQ84hNELv4smTjQQB3BYYB2ahAT9DdvZ6Fsc successfully which was 90KB in size and we are using WebAssembly.instantiate for this.

Yeah of course you can load wasm from URL, but the idea is to avoid asking permission for "Internet connection" and do everything locally.
Also you can't load a wasm more than 4Kb on the main thread. Do you use a worker to load the wasm in this case ?

**Comment by Niraj-Kamdar** [comment]
Nope, it worked perfectly fine on the main thread. Currently, it's breaking since they stopped including buffer and it throws the ReferenceError so not sure if they limit the size for loading wasm in the latest release.

**Comment by ritave** [comment]
Hey there,

The size of the WASM shouldn't be an issue, we're limiting the code size to 100mb, but we tested that it works at that size. I know that [SES](https://www.npmjs.com/package/ses) sandbox  interacts with browser optimisations hitting edge cases of their JavaScript engines, finding novel bugs or taking the slow path.

While we really want to support WASM better, including fixing those edge cases and having the ability to bundle wasm files, currently we're focused on getting what we have to the stable extension from Flask, and so official WASM support has taken a back-seat until then.

Generally the bleeding edge WASM research was done by an external person - @piotr-roslaniec. He had a lot of success with bundling WASM code as a plain base64 strings inside the bundle .js file and not using the `*Streaming` family of functions.

I'll raise the `global.self` issue with the SES developers.

**Comment by immortal-tofu** [comment]
> Generally the bleeding edge WASM research was done by an external person - @piotr-roslaniec. He had a lot of success with bundling WASM code as a plain base64 strings inside the bundle .js file and not using the `*Streaming` family of functions.

You're right, I think I was using `Compile` or `Instantiate` (which has a 4kb limitation in Chrome) instead of `instantiate` (which doesn't include a size limit as far as I see).

So for future viewer, here how I load a wasm from wasm-pack

```
import init from 'module-using-wasm-pack-export';
import wasm from 'module-using-wasm-pack-export/tfhe_bg.wasm';
import { base64ToArrayBuffer } from './utils';

export const loadWasm = async () => {
  // wasm is the base64 generated on compile by webpack
  const bytes = base64ToArrayBuffer(wasm.split(',')[1]);

  // IMPORTANT trick to allow wbindgen to find window -.-
  self.self = self;

  // Use init function provided by wasm-pack, which basically do an WebAssembly.instantiate with correct imports generated by wbindgen
  return init(bytes);
};
```

I close this issue since issues were related to usage of instantiateStreaming.
