### ISSUE TITLE
bug: getting buffer not found error after the Metamask flask extension upgrade

### ISSUE THREAD

**Issue by Niraj-Kamdar** [MetaMask/snaps-monorepo#1162]
Metamask Flask Verison: 10.23.2-flask.0
@metamask/snap-types Version: "^0.23.0"
@metamask/snaps-cli Version: "^0.23.0"

**Comment by FrederikBolding** [comment]
We do not auto polyfill `Buffer` anymore, you will have to polyfill that yourself in your snap source code, see: https://github.com/MetaMask/snaps-monorepo/issues/1021#issuecomment-1334992027

**Comment by ritave** [comment]
duplicate of #1021
