### ISSUE TITLE
SnapsWebpackPlugin doesn't work with devServer

### ISSUE THREAD

**Issue by immortal-tofu** [MetaMask/snaps-monorepo#1167]
Hello,
I'm trying to run snap from webpack + devServer configuration. There is a strange issue with the following configuration:

```
  devServer: {
    client: {
      logging: 'verbose',
    },
    port: 8080,
    liveReload: true,
    static: [
      {
        directory: './',
        publicPath: '/',
      },
    ],
  },
```

If I run `webpack serve` with this configuration, I get:

```
<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: http://localhost:8080/
<i> [webpack-dev-server] On Your Network (IPv4): http://192.168.0.20:8080/
<i> [webpack-dev-server] On Your Network (IPv6): http://[fe80::1]:8080/
<i> [webpack-dev-server] Content not from webpack is served from './' directory
<e> [webpack-dev-middleware] Error: Invalid params: '/xxx/metamask-snap/packages/snap/dist/bundle.js' is not a file or does not exist.
<e>     at validateFilePath (/xxx/metamask-snap/node_modules/@metamask/snaps-utils/src/fs.ts:135:11)
<e>     at async evalBundle (/xxx/metamask-snap/node_modules/@metamask/snaps-utils/src/eval.ts:16:3)
<e>     at async /xxx/metamask-snap/node_modules/@metamask/snaps-webpack-plugin/src/plugin.ts:108:9
```
So it seems `SnapsWebpackPlugin` is looking for a real file on the disk.

So I added `devMiddleware: { writeToDisk: true }` and now I have this error:

```
<e> [webpack-dev-middleware] Error: Process exited with non-zero exit code: 255
<e>     at ChildProcess.<anonymous> (/xxx/metamask-snap/node_modules/@metamask/snaps-utils/src/eval.ts:27:9)
<e>     at ChildProcess.emit (node:events:513:28)
<e>     at ChildProcess.emit (node:domain:489:12)
<e>     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
```

Obviously, `yarn webpack watch` and `yarn webpack build` works. SnapsWebpackPlugin only fails with devServer.

**Comment by FrederikBolding** [comment]
Hey @immortal-tofu 

It seems that the `client` part of `webpack-dev-server` is incompatible with Snaps due to an incompatibility with SES. If you disable `client` by setting it to `false`, the incompatible code looks to be removed and the build succeeds. 

While looking into this I found a number of improvements we could make to our Webpack plugin, these will be included in a future release.
