### ISSUE TITLE
Move the iFrame execution environment build system to LavaMoat

### ISSUE THREAD

**Issue by ritave** [MetaMask/snaps-monorepo#1184]
Currently, IFrameExecutionEnvironment is using WebPack to create the bundle that the snaps are run in. WebPack is vulnerable to supply chain attacks.

We should move to LavaMoat build system instead.

cc @naugtur 

See item 3 in https://docs.google.com/document/d/18KkaUWnplWy0Yg25hSTCAbnRSv8PzT-fC4jGTulg41U/edit#heading=h.i69ihvlqd4tl.

**Comment by ritave** [comment]
ManifestV3 will bundle the execution environment inside the extension itself, meaning that the ExecutionEnvironment will be build using the metamask-extension build system which uses LavaMoat already

**Comment by kenhkan** [comment]
We may need to port all webpack usage to browserify since LavaMoat doesn't support webpack yet (see https://github.com/MetaMask/metamask-extension/pull/17872).

**Comment by kenhkan** [comment]
We will revisit this after the effort of using MV3/webworkers.
