### ISSUE TITLE
Add snapshot of diff between raw SES bundle and the output of our build process to CI

### ISSUE THREAD

**Issue by rekmarks** [MetaMask/snaps-monorepo#1216]
The SES shim is fragile to modifications, and e.g. bundler optimizations may break its security guarantees. Although we do not currently run SES through a bundler, we do not have any automated guards against inadvertently modifying the SES shim bundle. We should therefore create a snapshot between a diff of the SES bundle as it appears in our dependencies and the version we ship to users. If the diff does not match the snapshot in CI, CI should fail, and we should be forced to update the snapshot manually after investigating why it changed.

**Comment by FrederikBolding** [comment]
Fixed in #1203 #1193
