### ISSUE TITLE
manifest shasum does not match computed shasum

### ISSUE THREAD

**Issue by emilbayes** [MetaMask/snaps-monorepo#1240]
Downloading the latest MetaMask Flask release from Github Releases (the one on MDN was oudated), and running `npm run serve` from the `browserify-snap` example I get the following error on `wallet_requestSnaps`:

```
MetaMask - RPC Error: Failed to fetch Snap "local:http://localhost:8081/": Invalid Snap manifest: manifest shasum does not match computed shasum..
```

The shasum that is added to the `snap.manifest.json` is `gcXDS2daNyzZ+uJEwxEiDckz5sGIipF5RFDmUDzj4/s=` however the shasum compute with the snippet from SIP-9 is `kIJdNIoopJmRYPZaQVDhNiCOiX4XX5hzKxMCJonebY8=` (using `sha256sum dist/snap.js | cut -d ' ' -f 1 | xxd -r -p | base64`).

MetaMask Flask version: `10.25.0-flask.0`
`snaps-monorepo` commit: `ac3752a`
Firefox Developer Edition: `110.0b9`

Tangential to this issue, but I'm not sure where to report it; the link to install Flask from https://metamask.io/flask/ actually installs MetaMask `10.22.2` and not a Flask version

**Comment by FrederikBolding** [comment]
The examples in this repository are updated to match a newer version of the Snaps Platform that is yet to ship to Flask. You should be able to use the examples from https://github.com/MetaMask/snaps-monorepo/tree/v0.27.1 with the latest version of Flask. We hope to bring the latest version of the Snaps Platform to Flask in the near future!

Also, thanks for reporting the download issue, looks to be only on Firefox. Will get that fixed!
