### ISSUE TITLE
Research which private keys we can verify in the extension

### ISSUE THREAD

**Issue by ritave** [MetaMask/snaps-monorepo#1265]
We want to sign snap-registry with a private key. We're considering either Ethereum private key infrastructure, or preferred, use x.509 certificates + revocation lists instead.

## Outcome
Research if it's feasible to verify x.509 signatures and revocation lists in the extension on the client side or do we need to fallback on Ethereum infrastructure

**Comment by kenhkan** [comment]
We have a plan B and this is not necessary.
