### ISSUE TITLE
Allow consumers to provide state encryption API

### ISSUE THREAD

**Issue by FrederikBolding** [MetaMask/snaps-monorepo#1319]
Some platforms may not be compatible with `metamask/browser-passworder`. So we need to allow for consumers to configure which encryption API to use.

**Comment by gantunesr** [comment]
@FrederikBolding @Mrtenz we just realized that the PR https://github.com/MetaMask/snaps-monorepo/pull/1055 included in version 0.27.0 moves the `metamask/browser-passworder` module from the SnapController to the RPC method `manageState`. This will require us to pass the methods `encrypt` and `decrypt` as hooks to the method

**Comment by Mrtenz** [comment]
@gantunesr My only worry with this is that consumers can provide a weak encryption algorithm. When you implement this, make sure to use something equivalent to `browser-passworder`.

**Comment by FrederikBolding** [comment]
@Mrtenz The alternative module used for mobile is this one: https://github.com/MetaMask/metamask-mobile/blob/main/app/core/Encryptor.js
