### ISSUE TITLE
Add sugar to `wallet_snap` declaration

### ISSUE THREAD

**Issue by ritave** [MetaMask/snaps-monorepo#1336]
[Currently, the `wallet_snap` permission definition is ugly](https://github.com/MetaMask/snaps-monorepo/blob/d7aad2aa735092a89375580f8eed0c03246c514d/packages/examples/examples/signer/packages/bitcoin/snap.manifest.json#L20-L29), we should provide a nicer sugar on top.

An example:
```json
"wallet_snap": [
  // shorthand form for snap ids
  "local:http://localhost:8100",
  "npm:my-snap"
  // a more explicit object could also be supported if necessary in the future
  { location: "ipfs://asdasdasd", checksum: "0x123123" }
]
```

**Comment by kenhkan** [comment]
This is a short-term solution. The Snaps dependency effort will be the long-term solution.
