### ISSUE TITLE
`Illegal invocation` after using `wallet_requestSnaps`

### ISSUE THREAD

**Issue by alanorwick** [MetaMask/snaps-monorepo#1345]
Function we are calling:
```
    async function connect() {
      await ethereum.request({
        method: 'wallet_requestSnaps',
        params: {
          [snapId]: {},
        },
      });
    }
```

Error we are seeing:
![Screen Shot 2023-04-12 at 2 22 00 PM](https://user-images.githubusercontent.com/14866363/231563207-7a8f85f6-84a0-4062-afc2-dc1060bd1be5.png)

**Comment by alanorwick** [comment]
Versions:
```
    "@metamask/auto-changelog": "^3.0.0",
    "@metamask/eslint-config": "^8.0.0",
    "@metamask/eslint-config-jest": "^8.0.0",
    "@metamask/eslint-config-nodejs": "^8.0.0",
    "@metamask/snaps-cli": "0.32.0",
    ```

**Comment by pragmatos** [comment]
It happens after update MetaMask Flask in Chrome to 10.28.2-flask.0, previous version was working correctly.
Any news?

**Comment by FrederikBolding** [comment]
This may be a known bug with usage of `atob` and `btoa`. If you are comfortable with it, you could try building the MM extension locally from https://github.com/MetaMask/metamask-extension to verify that it is fixed in an upcoming release.

**Comment by pragmatos** [comment]
> This may be a known bug with usage of `atob` and `btoa`. If you are comfortable with it, you could try building the MM extension locally from https://github.com/MetaMask/metamask-extension to verify that it is fixed in an upcoming release.

Could you help?
How correct to build last version of flask in https://github.com/MetaMask/metamask-extension. I'm getting extension errors in Chrome. Thanks

**Comment by alanorwick** [comment]
Any updates here?

**Comment by Montoya** [comment]
Hi @alanorwick , what is the value of snapId in your example? Is it a variable?

**Comment by zwilling** [comment]
I have the same issue with my snap since the flask 10.26->10.28.2-flask.0 update.

It works with an empty snap (same permissions, processRpcRequest empty) and breaks as soon as I add a reference to `import { stringToBytes, bytesToHex } from '@metamask/utils';` back in (tried @metamask/utils versions 3.5.0 and 5.0.1).
As @FrederikBolding suggested, it also breaks the same way when using `atob`.

This issue seems also related: https://github.com/MetaMask/metamask-extension/issues/18590

@Montoya The `snapId` I use is a string variable containing `local:http://localhost:8080`.

@FrederikBolding I built Flask 10.28.3-flask.0 and got the same error. When I try the same with the develop branch, it just loads forever after accepting permissions.

@pragmatos I built it with `yarn install; yarn dist --build-type flask`.

**Comment by alanorwick** [comment]
> Hi @alanorwick , what is the value of snapId in your example? Is it a variable?

Similar to @zwilling my snapId is coming in as `local:http://localhost:8083`. Broken on both local and hosted snapIds via npm. Example snapId for npm `npm:@quainetwork/quai-snap`

**Comment by FrederikBolding** [comment]
Looking into this to verify if it this isn't fixed on develop. Will respond back when I have more information

**Comment by FrederikBolding** [comment]
I'm seeing `atob` and `btoa` working on `develop` when building with `yarn dist --build-type flask`. 

Will look into the `@metamask/utils` problem that @zwilling mentioned.

**Comment by FrederikBolding** [comment]
I cannot reproduce the `@metamask/utils` problem. Is there a repository I can try to repro from @zwilling ?

**Comment by pragmatos** [comment]
> I'm seeing `atob` and `btoa` working on `develop` when building with `yarn dist --build-type flask`.
> 
> Will look into the `@metamask/utils` problem that @zwilling mentioned.

I tried `develop`, `atob` and `btoa` work. But there is another issue.
I included "polyfills" there are some functions override Object methods.
I got Error. With code bellow you could reproduce it.
` const TestObj = {
    testProp: {},
  };
  TestObj.testProp.toLocaleString = () => '';`
<img width="653" alt="Screenshot 2023-04-18 at 19 47 11" src="https://user-images.githubusercontent.com/15641426/232848386-079fe822-9e01-4075-b299-9a462029b2c4.png">

Between Extension has errors
 
<img width="679" alt="image" src="https://user-images.githubusercontent.com/15641426/232849165-bde3700c-51ce-4027-8c7e-d65c95da8600.png">
Any ideas?

**Comment by FrederikBolding** [comment]
@pragmatos Properties such as `toLocaleString` are protected, but you can modify them as such instead:

```
Reflect.defineProperty(obj, 'toLocaleString', { value: function toLocaleString(formatOpts, opts) { ... } });
```

See this patch as an example: https://github.com/MetaMask/test-snaps/blob/021bfda5f30f1f229dee0f18dc3731bb15ca1875/.yarn/patches/luxon-npm-3.1.0-16e2508500.patch

You may need to patch your dependencies if they are modifying props such as `toLocaleString`

**Comment by pragmatos** [comment]
> @pragmatos Properties such as `toLocaleString` are protected, but you can modify them as such instead:
> 
> ```
> Reflect.defineProperty(obj, 'toLocaleString', { value: function toLocaleString(formatOpts, opts) { ... } });
> ```
> 
> See this patch as an example: https://github.com/MetaMask/test-snaps/blob/021bfda5f30f1f229dee0f18dc3731bb15ca1875/.yarn/patches/luxon-npm-3.1.0-16e2508500.patch
> 
> You may need to patch your dependencies if they are modifying props such as `toLocaleString`

It's clear. But I use dependencies with `Intl`. `Intl` is not able in the snap.
Will `Intl' added in snaps? Thanks

**Comment by Montoya** [comment]
@pragmatos you may have to patch `Intl` or find a different library that works under SES. Here's a guide to patching: https://docs.metamask.io/snaps/how-to/troubleshoot#patch-dependencies

**Comment by zwilling** [comment]
> I cannot reproduce the `@metamask/utils` problem. Is there a repository I can try to repro from @zwilling ?

Thanks for checking @FrederikBolding . Trying to compile a minimal example reproducing it, I noticed that the issue is not caused by @metamask/utils. Instead it is caused by the library from where I imported a constant which is passed to the utils function.
Sorry for the false alarm. I did not expect such side effects from using a constant :see_no_evil: 

Will further investigate it. I also have luxon in my dependencies.

**Comment by FrederikBolding** [comment]
> @FrederikBolding With bare minimal dependencies I'm seeing `@metamask/snaps-utils` uses `"cron-parser": "^4.5.0"` which has a dependency on luxon. Just as you patched luxon in the test-snaps example, is it expected that all snaps run the luxon patch on `toLocaleString`?
> 
> Can't confirm it resolves after running the patch as well. Still working through applying the patch via yarn for the nested dependency.

Hmm, it is not intended for all snaps to need to patch `luxon`. What dependencies does your snap have that bring in `@metamask/snaps-utils`? Or are you using `@metamask/snaps-utils` directly in your snap?

**Comment by alanorwick** [comment]
@FrederikBolding from what I can tell `@metamask/snaps-ui`uses `@metamask/snaps-utils`.

We use `@metamask/snaps-ui` directly in the project. If `@metamask/snaps-ui` and `@metamask/key-tree` build okay as a base then it is likely a problem with another dependency. I've seen a few errors with `ethers@6.3.0` as well in regards to private methods. Going to dive into that more before opening up another issue.

**Comment by alanorwick** [comment]
> @FrederikBolding from what I can tell `@metamask/snaps-ui`uses `@metamask/snaps-utils`.
> 
> We use `@metamask/snaps-ui` directly in the project. If `@metamask/snaps-ui` and `@metamask/key-tree` build okay as a base then it is likely a problem with another dependency. I've seen a few errors with `ethers@6.3.0` as well in regards to private methods. Going to dive into that more before opening up another issue.

So purely with these dependencies I build fine:
```
    "@metamask/key-tree": "7.0.0",
    "@metamask/snaps-ui": "^0.32.2",
    "patch-package": "^6.5.1",
    "postinstall-postinstall": "^2.1.0"
    ```
   
After adding v5.4.3 of Ethers I see the Illegal Invocation again. If I upgrade Ethers to 6.3.0 I see an error on `mm-build` from the use of `#` to indicate a private method on the `ens-resolver`. 

If I had to guess where v5.4.3 would error it would be on the `buffer` package calling `Buffer.prototype.toLocaleString = Buffer.prototype.toString`.

**Comment by himanshuchawla009** [comment]
My Snap was working till last week and all of a sudden I am getting this error while making an API call inside snap. Don't know what I need to change here. 
<img width="824" alt="Screenshot 2023-04-21 at 12 20 46 PM" src="https://user-images.githubusercontent.com/14052374/233562193-decc5749-d727-43ff-b929-e4d325d3a89e.png">

**Comment by FrederikBolding** [comment]
A fix is part of Flask `10.29.0`, which we just submitted to Chrome and Firefox. So a fix should be rolling out as soon as they approve it.

**Comment by FrederikBolding** [comment]
Flask version `10.29.0` is rolling out on Chrome now. Let me know if this fixes your problems with `illegal invocation`

**Comment by alanorwick** [comment]
> Flask version `10.29.0` is rolling out on Chrome now. Let me know if this fixes your problems with `illegal invocation`

Fixed it, thank you.
