### ISSUE TITLE
Unable to detect web_clientVersion 

### ISSUE THREAD

**Issue by skunal8197** [MetaMask/snaps-monorepo#1381]
We have been closely following the [snaps documentation](https://docs.metamask.io/snaps/how-to/develop-a-snap/#detect-the-users-metamask-version) to accurately detect the user's MetaMask version.

Until recently, this method was working seamlessly. However, we have now observed that the call to fetch web3_clientVersion  returns MetaMask/v2.44.3, regardless of whether MetaMask Flask or the standard MetaMask is installed.

We are currently using snaps CLI 0.32.2 and Flask v10.29.0-flask.0. 

Any assistance or guidance on this issue would be highly appreciated.

**Comment by Montoya** [comment]
Do you have both MetaMask Flask and MetaMask installed in the same browser?

**Comment by skunal8197** [comment]
No

**Comment by skunal8197** [comment]
Ah, I realized that I had another enabled wallet extension that was also injecting an ethereum provider. This is what was causing the call to get `web3_clientVersion` to return `MetaMask/v2.44.3`. Disabling this wallet fixed the issue.
