### ISSUE TITLE
Error while running snap 'local:http://localhost:8080/': Cannot add property default, object is not extensible

### ISSUE THREAD

**Issue by aquiladev** [MetaMask/snaps-monorepo#1384]
Start receiving an error on snap installation:
```
Error when adding snap. Error: Error while running snap 'local:http://localhost:8080/': Cannot add property default, object is not extensible
  at o.command (common-0.js:3:145571)
  at async o.executeSnap (common-0.js:3:145182)
  at async n.withTimeout (common-0.js:3:217749)
  at async fe.N (common-0.js:3:181069)
  at async fe.A (common-0.js:3:176685)
  at async fe.processRequestedSnap (common-0.js:3:165353)
  at async fe.installSnaps (common-0.js:3:164303)
  at async Promise.allSettled (index 0)
e
```
Same error on installation from `npm`

Flask version `10.29.0-flask.0`
Snap repo https://github.com/aquiladev/bls-snap

**Comment by Montoya** [comment]
Hi, there have been many changes to the API. Please update "@metamask/snaps-cli" to version 0.30.0, then rebuild the snap. Let me know if you still see the error after updating.

**Comment by aquiladev** [comment]
I tried
```
"@metamask/snaps-cli": "^0.30.0",
"@metamask/snaps-types": "^0.30.0",
```
and latest versions
```
"@metamask/snaps-cli": "^0.32.2",
"@metamask/snaps-types": "^0.32.2",
```
same problem

**Comment by Montoya** [comment]
Hi, there's a problem in the snaps-cli that affects Ethers. We have a fix in snaps-cli 0.33.x. When that version is published, please try again and let me know if the problem persists.

**Comment by aquiladev** [comment]
Tried `@metamask/snaps-cli@^0.33.0-flask.1`, but same problem

**Comment by Montoya** [comment]
I'm sorry I didn't think of this before. The problem is likely that you need to add the ethereum-provider endowment: 

https://docs.metamask.io/snaps/reference/permissions#endowmentethereum-provider

Here is an example snap that uses ethers so you can see how it works: 

https://github.com/Montoya/mobymask-snap

You maybe have to modify the snap source code to use the objects that are exposed to the snap, one is wallet (for communicating with MetaMask) and one is ethereum (for communicating with the ethereum provider). So in my snap, after enabling this endowment, I can do: 

`const provider = new ethers.providers.Web3Provider(ethereum);`

**Comment by aquiladev** [comment]
tried `endowment:ethereum-provider` but no luck. I don't think it is needed 
I do not use ethereum provider from MetaMask in the snap, I construct separate provider from snap config
`new providers.JsonRpcProvider(network.rpcUrl, ...)`

**Comment by FrederikBolding** [comment]
Hey @aquiladev - This looks like a problem with `node-fetch`.

```
var global = getGlobal();
module.exports = exports = global.fetch;
if (global.fetch) {
  exports.default = global.fetch.bind(global);
}
exports.Headers = global.Headers;
exports.Request = global.Request;
exports.Response = global.Response;
```

You could try patching it to be something like this, which should work:
```
var global = getGlobal();
exports = {
  default: global.fetch,
  fetch: global.fetch,
  Headers: global.Headers,
  Request: global.Request,
  Response: global.Response,
};
module.exports = exports
```

**Comment by aquiladev** [comment]
does not help
<img width="1461" alt="Screenshot 2023-05-16 at 6 06 30 PM" src="https://github.com/MetaMask/snaps-monorepo/assets/1164492/8baf026d-16ee-4dfd-b631-087884b15776">

**Comment by FrederikBolding** [comment]
> does not help <img alt="Screenshot 2023-05-16 at 6 06 30 PM" width="1461" src="https://user-images.githubusercontent.com/1164492/238688990-8baf026d-16ee-4dfd-b631-087884b15776.png">

Do you have a branch where you've tried this that I can look at?

**Comment by aquiladev** [comment]
the problem can be reproduced in main branch https://github.com/aquiladev/bls-snap
or `upgrade-packages` branch with latest versions of packages

**Comment by aquiladev** [comment]
Thanks, I was doing this in a different way :/
