### ISSUE TITLE
Enforce coherence between RPC method hooks enum and implementation signature

### ISSUE THREAD

**Issue by rekmarks** [MetaMask/snaps-monorepo#287]
We currently specify the hooks required by an RPC method implementation in its "handler" object under the `methodHooks` property, which is an enum of sorts. We should consider adding some way to programmatically enforce consistency between the enum and the implementation function's signature in the `rpc-methods` package.

Example of shortcomings caused by the current types https://github.com/MetaMask/snaps-skunkworks/pull/286#pullrequestreview-909436294

**Comment by rekmarks** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Snaps--Core-615b3a7c08d2b20015eb6c4e/issues/MetaMask/snaps-skunkworks/287?planning-poker) with ZenHub @FrederikBolding @hmalik88 @ritave

**Comment by FrederikBolding** [comment]
I wonder what the ideal solution for this is, it might not be trivial to add types for this 🤔

**Comment by kenhkan** [comment]
Research on the best approach on this. If it's difficult, it may not be worth it.
