### ISSUE TITLE
Add e2e tests for snaps-cli

### ISSUE THREAD

**Issue by ritave** [MetaMask/snaps-monorepo#310]
This is to avoid users getting a new version from NPM and the cli breaks.

**Comment by rekmarks** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Snaps--Core-615b3a7c08d2b20015eb6c4e/issues/MetaMask/snaps-skunkworks/310?planning-poker) with ZenHub @FrederikBolding @hmalik88 @ritave
