### ISSUE TITLE
`wallet_requestSnaps` should fail for incompatible versions

### ISSUE THREAD

**Issue by rekmarks** [MetaMask/snaps-monorepo#612]
If a particular version of a snap is requested with `wallet_requestSnaps`, the request should fail if:
- Snap updates aren't supported.
- An update request is rejected.

We should verify the existing behavior. I think it's possible that `wallet_requestSnaps` returns with an error but doesn't reject due to how the method is designed. If that is the case, we should revisit the design / behavior of that method.

**Comment by hmalik88** [comment]
Is this a verified bug?

**Comment by bowensanders** [comment]
I believe confirmation that this bug does not exist is waiting for the next skunkworks release to be cut, and I will attempt to repro then.

This was done before the update ui and other things that would make this a non-issue

**Comment by rekmarks** [comment]
After discussing this with @FrederikBolding, we decided that `wallet_enable` should be atomic, i.e. either succeed completely or fail completely. If installing or updating any snap fails, then the entire operation should be reverted and the request should fail.

Updates present a problem, because while we can just remove successfully installed snaps, we currently do not have rollbacks for updates.

**Comment by rekmarks** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Snaps-Platform-615b3a7c08d2b20015eb6c4e/issues/MetaMask/snaps-monorepo/612?planning-poker) with Zenhub @FrederikBolding @Mrtenz @hmalik88

**Comment by FrederikBolding** [comment]
Explanation for my estimation: This issue is not the hard problem, the hard problem is rolling back if we fail. Hassan is working on that piece.
