### ISSUE TITLE
Expand snap confirmation capabilities

### ISSUE THREAD

**Issue by rekmarks** [MetaMask/snaps-monorepo#613]
(This may be irrelevant if we implement a blockkit like UI)

In addition to the confirmation via `snap_confirm`, we need:
- A prompt with plaintext input (yes/no)
- An alert (not yes/no, just "ok")

All of these things could be encompassed within the same permission, and ideally they should. Maybe something like `snap_dialog` or `_createDialog`, with a `type` enum. The alert type could always return `true`, and the prompt / confirmation would return `true`/`false` depending on the user's choice.

**Comment by FrederikBolding** [comment]
This may also benefit from #611 - `snap_prompt` could just take a custom UI element 😄

**Comment by Montoya** [comment]
There is desire among developers to at least have the option to use "Close" instead of "Reject / Approve"... maybe as a parameter on the method?

**Comment by FrederikBolding** [comment]
We should allow more customization, but the question is, will allowing custom UI in the prompt fix all the problems? If so, maybe that should be the priority

**Comment by Montoya** [comment]
The issue right now is people are using the custom confirmation for what are essentially alerts and the "Reject" button is irrelevant. Just having something to choose whether to have 1 button for OK vs 2 buttons for no/yes would solve the immediate issue. 

I know Erik also mentioned having a more generic snap_dialog permission which would support alerts, prompts, and confirmations. It seems like all this could be done without touching the issue of custom UI.

**Comment by rekmarks** [comment]
#799 added an RPC method for this purpose but we are still awaiting UI / integration in the extension.

**Comment by FrederikBolding** [comment]
We need to finish this up before stable.

**Comment by rekmarks** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Snaps-Platform-615b3a7c08d2b20015eb6c4e/issues/MetaMask/snaps-monorepo/613?planning-poker) with Zenhub @FrederikBolding @GuillaumeRx
