### ISSUE TITLE
Allows snaps to skip extension confirmations

### ISSUE THREAD

**Issue by ritave** [MetaMask/snaps-monorepo#737]
There's a lot of Snap use cases where people want to do the usual MetaMask operations, but without needing the user approval before executing. Getting access to private keys is a real overkill, while without those you have to get confirmation

A check box "don't ask for confirmation from this Snap" would be an easish solution.
A permission set by that checkbox that’s checked during normal `window.provider` / `wallet.request` operations.

**Comment by rekmarks** [comment]
This is getting to a real problem, but the authority granted by a permission like this is extremely broad and therefore hard to reason about and therefore unsuitable in production. We can consider things such as spending limits and more narrowly scoped signatures to minimize confirmations, but "let this thing do whatever Ethereum operations it wants" is out of the question.

I'll close this and we can open issues for more narrowly defined permissions.
