### ISSUE TITLE
UI standardization

### ISSUE THREAD

**Issue by eriknson** [MetaMask/snaps-monorepo#778]
Let's standardize the popup screens of our UI to look aligned, see attached image & [design](https://www.figma.com/file/kz987q7xsI9NzGvUZrc8LF/Snaps-UI?node-id=611%3A13846).

<img width="2080" alt="Frame 142004" src="https://user-images.githubusercontent.com/34306844/191554868-05bc4f86-1217-49bd-9ed5-faf4b69ff72d.png">

**Comment by ritave** [comment]
Oooh, I like the new custom popup. I see it's not using monospace font anymore though. Do you think we should we use a monospace one or a normal one?

**Comment by rekmarks** [comment]
Closing in favor of https://github.com/MetaMask/metamask-extension/issues/16462
