### ISSUE TITLE
Snaps Crash After Reimporting Seed Phrases to MetaMask Flask

### ISSUE THREAD

**Issue by louzhixian** [MetaMask/snaps-monorepo#818]
Steps to reproduce:
1. install and use the snaps as usual
2. re-import seed phrases to MetaMask Flash without uninstalling the plugin
3. access any snap and it will crash

Here’s a video I recorded to show that the same issue happened in 3 snaps: fil-snap, btc-snap, up-seedless-snap.

https://www.loom.com/share/32f8629097214544be19063e1ea17b1f

**Comment by FrederikBolding** [comment]
Fixed in https://github.com/MetaMask/metamask-extension/pull/16228
