### ISSUE TITLE
MultiChain provider doesn't work with template-snap-monorepo

### ISSUE THREAD

**Issue by ritave** [MetaMask/snaps-monorepo#826]
<img width="976" alt="Screenshot 2022-10-08 at 10 49 50" src="https://user-images.githubusercontent.com/1614945/194717126-2b9b7f76-8086-4b81-a34a-a4494e1ccbdd.png">

version `0.22.1`

**Comment by FrederikBolding** [comment]
https://github.com/ianstormtaylor/superstruct/issues/612

**Comment by FrederikBolding** [comment]
This is not a problem anymore after the template-snap-monorepo stopped using CRA.
