### ISSUE TITLE
onTransaction is called repeatedly 

### ISSUE THREAD

**Issue by ritave** [MetaMask/snaps-monorepo#828]
When a user selects the snap tabntje onTransaction is not called once but recalled multiple times into infinity

**Comment by FrederikBolding** [comment]
My guess would be that the component rerenders more often than we think and our current hook doesn't expect that.

cc @GuillaumeRx

**Comment by GuillaumeRx** [comment]
Yes, it seems like one of the parent components updates more often then we thought. This may be due to the transaction logic.

Duplicate of #816

**Comment by ritave** [comment]
The call should happen only the first time during the first render and then the data should be cached in the UI

**Comment by FrederikBolding** [comment]
> The call should happen only the first time during the first render and then the data should be cached in the UI

Opened a PR that fixes this, but have asked for feedback from the extension team
