### ISSUE TITLE
@metamask/key-tree not working in template-snap-monorepo

### ISSUE THREAD

**Issue by 0xPenryn** [MetaMask/snaps-monorepo#837]
<img width="752" alt="Screenshot 2022-10-10 at 12 53 48 PM" src="https://user-images.githubusercontent.com/29718876/194926189-ca24160d-7daf-40ab-8586-38c117f66540.png">

This is @ritave hello everyone

**Comment by Mrtenz** [comment]
I think this is an issue with `template-snap-monorepo`, not with `key-tree`.

**Comment by FrederikBolding** [comment]
This will be fixed when we stop using `Buffer` in `key-tree`

**Comment by Mrtenz** [comment]
This should already be fixed on the latest template Snap, as Gatsby supports Buffer out of the box.
