### ISSUE TITLE
Snap checksum should include all inputs in the calculation

### ISSUE THREAD

**Issue by rekmarks** [MetaMask/snaps-monorepo#847]
Snap shasums are currently computed with only the source code as input. This means that someone could in theory (if not currently in practice because of npm) publish "the same" snap with different sets of permissions.

We should see if we can simply do what npm does.

### Outcome
The new algorithm needs to get a list of all assets, including the manifest itself, calculate the checksum over all of them in a reproducible way and verify that checksum during installation.

**Comment by rekmarks** [comment]
@ritave points out that the manifest can be a shasum input as long as the shasum field is emptied.

**Comment by ritave** [comment]
NPM doesn't calculate checksums, but [Github does](https://docs.github.com/en/actions/learn-github-actions/expressions#hashfiles), and it's over multiple files.

**Comment by rekmarks** [comment]
> NPM doesn't calculate checksums, but [Github does](https://docs.github.com/en/actions/learn-github-actions/expressions#hashfiles), and it's over multiple files.

npm does calculate checksums: https://docs.npmjs.com/cli/v9/commands/npm-doctor#validate-the-checksums-of-cached-packages

**Comment by ritave** [comment]
It calculates the checksum (one) of a tarball, which is also non-deterministic for our use-case due to tarballs not being sorted internally. Not checksums (many) of multiple files concatenated.

**Comment by ritave** [comment]
Note - Consider a situation where two files (eg bundle and icon) point to the same file

**Comment by ritave** [comment]
Should the checksum include the manifest itself? Does it increase security?

**Comment by ritave** [comment]
To calculate the checksum over the manifest, we need to serialize it in a reproducible waywithout the checksum field and calculate over that intermediary.

Take a look at JSum and fast-json-stable-stringify packages
