### ISSUE TITLE
Error: @metamask/snap-utils tried to access @babel/types, but it isn't declared in its dependencies

### ISSUE THREAD

**Issue by snogcel** [MetaMask/snaps-monorepo#850]
Hello,

I am trying to use @metamask/snaps-webpack-plugin in https://github.com/dashpay/platform/tree/master/packages/js-dash-sdk in order to resolve some SES errors I'm running in to when compiling a snap I'm working on that supports the Dash Network. 

When I require @metamask/snaps-webpack-plugin in https://github.com/dashpay/platform/blob/master/packages/js-dash-sdk/webpack.base.config.js and add to the plugins array, I receive the following error when running yarn build:

$ yarn build
[webpack-cli] Failed to load 'C:\Users\username\Projects\platform\packages\js-dash-sdk\webpack.config.js' config     
[webpack-cli] Error: @metamask/snap-utils tried to access @babel/types, but it isn't declared in its dependencies; this make
s the require call ambiguous and unsound.

Required package: @babel/types (via "@babel\types")
Required by: @metamask/snap-utils@npm:0.22.2 (via C:\Users\username\Projects\platform\.yarn\cache\@metamask-snap-util
s-npm-0.22.2-8338447099-1cc2c7b346.zip\node_modules\@metamask\snap-utils\dist\)

I'm not sure if this is a Windows-related error (I'm using visual studio code / git bash), or something else entirely. Would anyone be able to advise on what is going on here?

Thanks!

**Comment by Mrtenz** [comment]
It looks like we mistakenly put `@babel/types` in `devDependencies` while it is used for post processing in the Webpack plugin (as well as the other bundler plugins). Will do a PR to fix this shortly!
