### ISSUE TITLE
Snaps notification no longer works

### ISSUE THREAD

**Issue by paulfears** [MetaMask/snaps-monorepo#851]
When I call wallet.notify
I get the error
background-0.js:13 Uncaught (in promise) Error: Tried to pause a not running Timer
no notification shows

**Comment by FrederikBolding** [comment]
@paulfears What kind of notification are you trying to show and which version of MetaMask Flask are you using? Do you have some source code available for what you are trying to do?

**Comment by paulfears** [comment]
New update fixed issue
