### ISSUE TITLE
Standardize RPC method parameters

### ISSUE THREAD

**Issue by FrederikBolding** [MetaMask/snaps-monorepo#870]
Currently these use a mix of parameters passed by position and by name

**Comment by FrederikBolding** [comment]
Perhaps we should just prefer by name for everything?

**Comment by hmalik88** [comment]
I vote for params by name.

**Comment by david0xd** [comment]
Here is some report on the current situation:

Restricted methods:
- `wallet_snap_*` - [{named}]
- `snap_confirm` - [{named}]
- `snap_dialog` - {named}
- `snap_getBip32Entropy` - {named}
- `snap_getBip32PublicKey` - {named}
- `snap_getBip44Entropy` - {named}
- `snap_manageState` - [positional]
- `snap_notify` - [{named}] 

Permitted methods:
- `wallet_enable` - [{named}]
- `wallet_getSnaps` - no params
- `wallet_installSnaps` - [{ dynamic_key: {value} }] 
- `wallet_invokeSnap` - [positional]

`[{named}]` - Requires array in which first object is taken. Object usually have specific parameter type.
`{named}` - Requires only an object which is typed.
`[positional]` - Array entries are taken on specific positions and turned into parameters.
`[{ dynamic_key: {value} }] ` - Array with one object containing dynamic keys which represent snap ID. (Specific only to `wallet_installSnaps`).
