### ISSUE TITLE
Implement Snaps allowlist solution

### ISSUE THREAD

**Issue by FrederikBolding** [MetaMask/snaps-monorepo#871]
Snaps release in the main extension in v1.0.0 will be based on an allow-list of third-party audited Snaps. A technical solution needs to be implemented that allows the extension to reference that list during install time.

### Outcome
- `snaps-registry` repository that will be polled by the extension
- Data schema for the allow-list
- TypeScript types for the schema
- Extension using that registry for allowing snaps in Production

**Comment by FrederikBolding** [comment]
Reference: https://github.com/MetaMask/snaps-monorepo/pull/479

**Comment by FrederikBolding** [comment]
> Could this be implement using the blocklist? Ref: #869

Yeah, we could refactor the blocklist logic to function as an allow list as well.

**Comment by ritave** [comment]
Additionally, the versioning needs to verify both the checksum of the tarball and the npm version, because it might be possible to replace npm package version in some fun ways (`npm unpublish --force`).
