### ISSUE TITLE
Add internal roll back functionality

### ISSUE THREAD

**Issue by FrederikBolding** [MetaMask/snaps-monorepo#872]
For failed updates we should have an internal roll back functionality.

**Comment by ritave** [comment]
We decided not to do rollbacks previously

**Comment by FrederikBolding** [comment]
> We decided not to do rollbacks previously. It's not a problem in practice for most of the applications in the world that have update functionallity.

When @rekmarks and I were discussing it yesterday we decided we might need it for when `wallet_enable` fails halfway through and we need to revert back to the previous state.

**Comment by ritave** [comment]
What failure mode do you have in mind?

Is it something breaking on our side, or breaking on the snap side?

If on the snap side, the above point stands - millions of apps are upgredable without rollbacks, and until we find the need for rollbacks based on real usage reports, I'm pretty sure that would waste a lot of time.

**Comment by FrederikBolding** [comment]
> What failure mode do you have in mind?
> 
> Is it something breaking on our side, or breaking on the snap side?
> 
> If on the snap side, the above point stands - millions of apps are upgredable without rollbacks, and until we find the need for rollbacks based on real usage reports, I'm pretty sure that would waste a lot of time.

If we want `wallet_enable` to be an atomic operation that either succeeds or fails it would be weird for there to be side effects in case of failure. 

For example, if I request to install 2 snaps and update 2 existing snaps in the same `wallet_enable`, if either of those 4 operations fail I would expect nothing to have changed. For snap install, that is trivial, we can just remove snaps that were installed as part of the process. But to handle updates we would need to be able to restore the state of the SnapController before the `wallet_enable` process began. A potential solution for this is an internal rollback mechanism that is exclusively used if anything in the update process fails, not leveraged by users to roll back.

**Comment by rekmarks** [comment]
Superseded by #893
