### ISSUE TITLE
Throw on Math.random() in snap

### ISSUE THREAD

**Issue by ritave** [MetaMask/snaps-monorepo#885]
People use `Math.random()` as insecure entropy inside snaps. This should throw an error instead of silently returning undefined results.

https://github.com/matCzelusniak/snapXrpl/blob/0116ac8dee9bd5510bdc9c770d365dc6e14063ef/packages/snap/src/index.ts#L59

**Comment by rekmarks** [comment]
Closing in favor of https://github.com/MetaMask/snaps-monorepo/issues/948
