### ISSUE TITLE
Disable `localhost:` snaps outside of Flask

### ISSUE THREAD

**Issue by rekmarks** [MetaMask/snaps-monorepo#896]
`localhost:` snaps are not something that we ever want to support in stable MetaMask, and we should ensure that they are disabled in stable distributions.

### Outcome
1. Snaps that are fetched from localhost should only be available in Flask distribution.
2. The user should be notified that this snap is a debug one and will not be loaded.

**Comment by ritave** [comment]
I might have some refactor coming in replacing this issue. Stand by
