### ISSUE TITLE
CLI logs error twice

### ISSUE THREAD

**Issue by GuillaumeRx** [MetaMask/snaps-monorepo#913]
We currently use `logError` to log errors in CLI resulting in logging twice the error since we need to throw after.

![image.png](https://images.zenhubusercontent.com/6204026449ea8e1f79b7af65/2eeec137-e117-4d2b-bb94-3a715918ed76)

**Comment by rekmarks** [comment]
@GuillaumeRx could this be solved by simply removing `logError` and just throwing instead? `logError` is an artifact from the days when we used `process.exit(1)`.
