### ISSUE TITLE
Allow custom UI in `snap_dialog` and transaction insights

### ISSUE THREAD

**Issue by FrederikBolding** [MetaMask/snaps-monorepo#934]
We should build and allow for a subset of the planned custom UI features to be used with `snap_dialog` and transaction insights. For stable, this is going to be a limited subset of the planned SIP: https://metamask.github.io/SIPs/SIPS/sip-7

For this issue we are going to need logic to generate the JSON-based UI, some logic to render it and adding this to existing RPC commands and flows.

**Comment by rekmarks** [comment]
This should be turned into an epic as it consists of three separate issues:
- Custom UI builder + underlying JSON representation
- The renderer in the extension
- Integrating all of these pieces for use with `snap_dialog`

**Comment by eriknson** [comment]
Here's the current [figma including initial components](https://www.figma.com/file/kz987q7xsI9NzGvUZrc8LF/Snaps-UI?node-id=1310%3A27887)
