### ISSUE TITLE
Review snap state encryption implementation

### ISSUE THREAD

**Issue by rekmarks** [MetaMask/snaps-monorepo#944]
The snap state encryption implementation should undergo a security/cryptography review. Finally, it must be re-implemented once #943 is completed.

**Comment by kenhkan** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Snaps-615b3a7c08d2b20015eb6c4e/issues/MetaMask/snaps-monorepo/944?planning-poker) with Zenhub @david0xd @FrederikBolding @GuillaumeRx @hmalik88 @Mrtenz @ritave
