### ISSUE TITLE
Help wanted: fetch() request are canceled

### ISSUE THREAD

**Issue by FreshHillyer** [MetaMask/snaps-monorepo#952]
Some weird problem bothers me when I want to access remote API in OnTransactionHandler. 
I turned on the` endowment:network-access` permission and used the following code to `fetch` the network API, I found that all my fetch requests were canceled from the metamsk flask background.html.

```
export const onTransaction: OnTransactionHandler = async ({
  transaction,
  chainId,
}) => {
  let json_ret = "";
  const API_ENDPOINT = 'https://api.github.com/users/MetaMask';
  fetch(API_ENDPOINT).then((res)=> {
      if (!res.ok) {
        throw new Error('Bad response from server');
      }
      return res.json();
    }).then((json)=> {
      console.log(json)
      json_ret = json
    }).catch((err) => console.error(err));
  

  const insights = {["result"]:json_ret};
  return { insights };
};
```

I am new to snap, can some body help...

**Comment by ritave** [comment]
When a snap returns, it cancels all ongoing executing communication.

You need to await your fetch to manipulate the results

```typescript
export const onTransaction: OnTransactionHandler = async ({
  transaction,
  chainId,
}) => {
  let json_ret = "";
  const API_ENDPOINT = 'https://api.github.com/users/MetaMask';
  const res = await fetch(API_ENDPOINT);
  if (!res.ok) {
    throw new Error('Bad response from server');
  }
  const json = await res.json();
  console.log(json); 

  const insights = {["result"]:json};
  return { insights };
};
```

**Comment by FreshHillyer** [comment]
> When a snap returns, it cancels all ongoing executing communication.
> 
> You need to await your fetch to manipulate the results
> 
> ```ts
> export const onTransaction: OnTransactionHandler = async ({
>   transaction,
>   chainId,
> }) => {
>   let json_ret = "";
>   const API_ENDPOINT = 'https://api.github.com/users/MetaMask';
>   const res = await fetch(API_ENDPOINT);
>   if (!res.ok) {
>     throw new Error('Bad response from server');
>   }
>   const json = await res.json();
>   console.log(json); 
> 
>   const insights = {["result"]:json};
>   return { insights };
> };
> ```

thanks! it works!
