### ISSUE TITLE
Consider exposing origin in transaction insights

### ISSUE THREAD

**Issue by ritave** [MetaMask/snaps-monorepo#956]
This has been talked about internally and [people are asking for this](https://github.com/MetaMask/snaps-monorepo/discussions/474#discussioncomment-4133429).

This is useful information and we currently don't expose only due to technical reasons.

**Comment by FrederikBolding** [comment]
https://github.com/MetaMask/snaps-monorepo/pull/902

**Comment by lljxx1** [comment]
@FrederikBolding Thanks, Would like to know when this will ship in MetaMask Flask?

**Comment by FrederikBolding** [comment]
We are still working out the details, so it'll be a few weeks before we ship it.

**Comment by rekmarks** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Snaps-Platform-615b3a7c08d2b20015eb6c4e/issues/MetaMask/snaps-monorepo/956?planning-poker) with Zenhub @FrederikBolding @Mrtenz

**Comment by FrederikBolding** [comment]
This is pending some changes in the extension.

**Comment by lljxx1** [comment]
@rekmarks @FrederikBolding BTW, Is there has similar insight feature for the `signTypedData_v3` EIP-712 sign request?

**Comment by kenhkan** [comment]
Closing in favor of https://github.com/MetaMask/metamask-extension/issues/16631
