### ISSUE TITLE
Allow deriving child nodes with `getBip32PublicKey`

### ISSUE THREAD

**Issue by rekmarks** [MetaMask/snaps-monorepo#967]
We should permit deriving child public keys using `getBip32PublicKey`, see #752.

**Comment by rekmarks** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Snaps-Platform-615b3a7c08d2b20015eb6c4e/issues/MetaMask/snaps-monorepo/967?planning-poker) with Zenhub @FrederikBolding @ritave @Mrtenz

**Comment by FrederikBolding** [comment]
This is already possible with the currently released version of the Snaps platform. A misunderstanding in how caveats were implemented caused us to think this wasn't possible.
