### ISSUE TITLE
Support html in notification

### ISSUE THREAD

**Issue by Julink-eth** [MetaMask/snaps-monorepo#976]
It would be nice to be able to display custom html such as bold/link tags in a notification message.

**Comment by ritave** [comment]
We're currently [experimenting with custom UIs](https://github.com/MetaMask/SIPs/blob/main/SIPS/sip-7.md) for snaps. And while we don't have any timelines, we'll be focusing on this as soon as we possibly can.

**Comment by Julink-eth** [comment]
Thanks for the info @ritave
