### ISSUE TITLE
Better error handling for endowments used during snap installation

### ISSUE THREAD

**Issue by ritave** [MetaMask/snaps-monorepo#988]
A common occurrence is that people try to do execution during snap installation, which either never returns or throws an error. For example https://github.com/MetaMask/snaps-monorepo/discussions/985#discussioncomment-4177521

Snap installation currently has poor error reporting and it should be easier to understand what's happening.

Or better yet [move to lazy initialisation](https://github.com/MetaMask/snaps-monorepo/issues/465), which merges how we handle both cases into one implementation.

**Comment by kenhkan** [comment]
To investigate whether this is fixed by the one pop-up

**Comment by hmalik88** [comment]
Yes, this is solved, build errors are propagated to the one pop-up.

**Comment by hmalik88** [comment]
![Screenshot 2023-03-27 at 5.33.26 PM.png](https://images.zenhubusercontent.com/6179a00f475464c462022d7c/ddce8519-8848-4da0-988c-183aac59f223)

Based on the source code in the linked issue #985
