### ISSUE TITLE
Forbid snaps from requesting `eth_accounts`

### ISSUE THREAD

**Issue by rekmarks** [MetaMask/snaps-monorepo#990]
**The problem**

There are multiple edge cases with `eth_accounts`, additionally, that RPC is strongly linked to dApp set-up process, and the assumption this RPC does are related to that. For example, `eth_accounts` returns one account, while snap can get all the accounts using private key. UI problems, etc.

It's confusing for everyone involved - users, developers and MM devs.

Forbid snaps from requesting `eth_accounts`

We need to ensure that snaps cannot request `eth_accounts` in any way for stable. For Flask we can do whatever, but it must not be permitted under any circumstance in stable.

### Outcome

1. Fails with error message when `eth_accounts` is used.
2. Describe why we're focusing more on multi-chain methods and `snap_dialog` in a comment in this issue.
3. The message in the error should point to this issue for discussion.

**Comment by paulfears** [comment]
Can it be a permission, that must be accepted by the user every time?

**Comment by andyv09** [comment]
How would snaps get the current account address if `eth_accounts` gets removed from snaps

**Comment by Montoya** [comment]
4. To this end, I think we should spend more time thinking about [how to address eth methods](https://app.zenhub.com/workspaces/snaps-615b3a7c08d2b20015eb6c4e/issues/gh/metamask/snaps-monorepo/990). It seems like there are three different types of methods that are relevant to snaps: 

    1. Methods that allow snaps to read public blockchain data (block number, contract data)
    2. Methods that allow snaps to read data about a user (account addresses, balances)
    3. Methods that allow snaps to write to the blockchain or make transactions
    
    It seems like there should be permissions or endowments for each of these categories, which go from least risky to most risky. It also seems like we should lock down what `snaps` can do with the wallet global and make sure we are only allowing methods we feel comfortable with.

**Comment by andyv09** [comment]
@Montoya Our idea is to make our snap "account based", meaning internal settings and data are specific to an account. Hence we use `eth_requestAccounts` to get the address of the currently selected account.  We want to use MetaMask accounts, so there is no need to create and manage accounts inside snap and keep account switching as simple as it already is.

For example, User can store some data under Account 1, then switch to Account 2 and store something else under that account.

**Comment by paulfears** [comment]
We use eth_requestAccounts to allow users to swap between eth and algorand. This way the eth can be put directly into a users main account, and they can swap to algorand with etherium held in their main account.

**Comment by GuillaumeRx** [comment]
Use the new SnapController arg excludedPermissions introduced in #1125 to retrict it on the extension side.

**Comment by GuillaumeRx** [comment]
We're disabling usage of `eth_accounts` inside snaps. Due to multiple edge-cases and `eth_accounts` not being designed to be used in snaps, our effort being directed to the Multi-Chain provider. In the meantime you can use `snap_getBip32Entropy`.

**Comment by rekmarks** [comment]
To be clear, we will try to enable `eth_accounts` for snaps in the future, we just don't know if it will be worth the effort at this time.
